apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "explorer.fullname" . }}-keystore1
  labels:
    app: {{ template "explorer.name" . }}
    chart: {{ template "explorer.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- (.Files.Glob "crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/cc6590c71e599f89e1a20b6bfc0a84874dc60173b14a2ccb19d7c60e8f8151d3_sk").AsConfig | nindent 2 }}
