apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "explorer.fullname" . }}-cryptoca1
  labels:
    app: {{ template "explorer.name" . }}
    chart: {{ template "explorer.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- (.Files.Glob "crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt").AsConfig | nindent 2 }}
